version: '3.7'

services:
    gameserver:
        image: game:latest
        build:
            context: .
            dockerfile: ./Dockerfile
        entrypoint: 'node --inspect=0.0.0.0:9001 out/app/GameServer.js'
        deploy:
            replicas: 2
            restart_policy:
                condition: unless-stopped
                delay: 5s
                max_attempts: 3
                window: 120s
        environment:
            NODE_ENV: 'development'

            name: 'GameServer'
            pm_id: '1'

            PORT: 3000
            REDIS_HOST: redis
            REDIS_PORT: 6379
            ARANGODB_HOST: arangodb
            ARANGODB_PORT: 8529
        ports:
            - 3000:3000
            - 9001:9001
        depends_on:
            - redis
            - arangodb
        volumes:
            - './out/app:/app/out/app'
            - './var:/app/var'
        restart: unless-stopped

    webserver:
        image: game:latest
        build:
            context: .
            dockerfile: ./Dockerfile
        entrypoint: 'node --inspect=0.0.0.0:9002 out/app/WebServer.js'
        deploy:
            replicas: 2
            restart_policy:
                condition: unless-stopped
                delay: 5s
                max_attempts: 3
                window: 120s
        environment:
            NODE_ENV: 'development'

            name: 'WebServer'
            pm_id: '1'

            PORT: 3001
            REDIS_HOST: redis
            REDIS_PORT: 6379
            ARANGODB_HOST: arangodb
            ARANGODB_PORT: 8529
        ports:
            - 3001:3001
            - 9002:9002
        depends_on:
            - redis
            - arangodb
        volumes:
            - './out/app:/app/out/app'
            - './var:/app/var'
        restart: unless-stopped

    redis:
        image: redis
        deploy:
            replicas: 1
            restart_policy:
                condition: unless-stopped
                delay: 5s
                max_attempts: 3
                window: 120s
        ports:
            - 6379:6379
        restart: unless-stopped

    arangodb:
        image: arangodb
        deploy:
            replicas: 1
            restart_policy:
                condition: unless-stopped
                delay: 5s
                max_attempts: 3
                window: 120s
        environment:
            ARANGO_NO_AUTH: 'true'
            ARANGO_STORAGE_ENGINE: 'mmfiles'
        ports:
            - 8529:8529
        volumes:
            - type: volume
              source: dbPersist
              target: /var/lib/arangodb3
              volume:
                  nocopy: true
        restart: unless-stopped

volumes:
    dbPersist:
