version: '3.7'

services:
    gameserver:
        image: game:latest
        build:
            context: .
            dockerfile: ./Dockerfile
        entrypoint: 'node --inspect=0.0.0.0:9001 out/app/GameServer.js'
        deploy:
            replicas: 2
        environment:
            NODE_ENV: 'development'

            name: 'GameServer'
            pm_id: '1'

            PORT: 3000
            REDIS_HOST: redis
            REDIS_PORT: 6379
            ARANGODB_HOST: arangodb
        ports:
            - 3000:3000
            - 9001:9001
        depends_on:
            - redis
            - arangodb
        volumes:
            - './out/app:/app/out/app'
            - './var:/app/var'
        restart: unless-stopped

    webserver:
        image: game:latest
        build:
            context: .
            dockerfile: ./Dockerfile
        entrypoint: 'node --inspect=0.0.0.0:9002 out/app/WebServer.js'
        environment:
            NODE_ENV: 'development'

            name: 'WebServer'
            pm_id: '1'

            PORT: 3001
            REDIS_HOST: redis
            REDIS_PORT: 6379
            ARANGODB_HOST: arangodb
        ports:
            - 3001:3001
            - 9002:9002
        depends_on:
            - redis
            - arangodb
        volumes:
            - './out/app:/app/out/app'
            - './var:/app/var'
        restart: unless-stopped

    redis:
        image: redis

    arangodb:
        image: arangodb
        environment:
            ARANGO_NO_AUTH: 'true'
