version: "3.7"

services:

    gameserver:
        build:
            context: .
            dockerfile: ./Dockerfile
        entrypoint: "node out/app/GameServer.js"
        environment:
            NODE_ENV: "development"

            name: "WebServer"
            pm_id: "1"

            PORT: 3000
            REDIS_HOST: redis
            REDIS_PORT: 6379
            ARANGODB_HOST: arangodb
        ports:
            - 3000:3000
        depends_on:
            - redis
            - arangodb

    webserver:
        build:
            context: .
            dockerfile: ./Dockerfile
        entrypoint: "node /app/out/app/WebServer.js"
        environment:
            NODE_ENV: "development"

            name: "WebServer"
            pm_id: "1"

            PORT: 3001
            REDIS_HOST: redis
            REDIS_PORT: 6379
            ARANGODB_HOST: arangodb
        ports:
            - 3001:3001
        depends_on:
            - redis
            - arangodb

    redis:
        image: redis

    arangodb:
        image: arangodb
        environment:
            ARANGO_NO_AUTH: "true"
