# The redis server only supports 15 different databases which can be willed
# with any datatypes.
redis:
    # This Database is used to cache the configuration to reduce hard disc drive
    # usage and to connect other services with the rest of the world, which have
    # no access to the config.
    default: 0

    # This is the session store to support multiple instances of a service and to
    # reduce memory leaks
    sessions: 1

    # Not yet in use ==============================================================
    database3: 2
    database4: 3
    database5: 4
    database6: 5
    database7: 6
    database8: 7
    database9: 8
    database10: 9
    database11: 10
    database12: 11
    database13: 12
    database14: 13
    database15: 14

# The arangodb databases will be confugured later if it is necessary
arangodb:
