version: "3.8"

services:
    gameServer:
        environment:
            NAME: "GameServer"
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
                max_attempts: 3
        restart: unless-stopped

    webServer:
        environment:
            NAME: "WebServer"
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
                max_attempts: 3
        restart: unless-stopped

    redis:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                max_attempts: 3
        restart: unless-stopped

    arangoDB:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                max_attempts: 3
        restart: unless-stopped

    redisInsight:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                max_attempts: 3
        restart: unless-stopped
