version: "3.8"

services:
    gameServer:
        # paths relative to image root
        entrypoint: "npx nodemon -L --inspect=0.0.0.0:9001 out/app/server/GameServer.js"
        ports:
            - 9001:9001
        deploy:
            replicas: 1

    webServer:
        # paths relative to image root
        entrypoint: "npx nodemon -L --inspect=0.0.0.0:9002 out/app/server/WebServer.js"
        ports:
            - 9002:9002
        deploy:
            replicas: 1
